# -*- coding: utf-8 -*-
"""Urban 311 Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jf3rVMMPq9E0O_dUw4Zr9SkL_ynZKrgZ
"""

import pandas as pd
import matplotlib.pyplot as plt

three_one_one = pd.read_csv("data_311_2023_-512369008947879443.csv")
print("Num columns:", three_one_one.shape[1])
for c in three_one_one.columns:
  print(c)

issue_types = sorted(three_one_one["issue_type"].dropna().astype(str).unique())
print("Unique issue_type count:", len(issue_types))
for it in issue_types:
    print(it)

road_keywords = ["POTHOLE", "ROAD SURFACE", "PAVEMENT", "ASPHALT", "DIP", "DEPRESSION", "DROP - OFF", "CURB"]
s = three_one_one["issue_type"].astype(str)
is_road_surface = False
for k in road_keywords:
    is_road_surface = is_road_surface | s.str.contains(k, case=False, na=False)
three_one_one["is_transport"] = is_road_surface

transport_n = int(three_one_one["is_transport"].sum())
total_n = len(three_one_one)
other_n = total_n - transport_n

colors = ["#4C78A8", "#D9D9D9"]
plt.figure(figsize=(8, 8))
plt.pie([transport_n, other_n],
        labels = ["Transportation Related", "All other issues"],
        colors = colors,
        autopct = lambda p: f"{p:.1f}%",
        startangle=90,
        explode=(0.1, 0))
plt.title("Share of 311 Request: Transportation VS All Other Issues",
          fontsize = 18,
          fontweight = "bold",
          pad = 14)
plt.tight_layout()
plt.show()

transport_df = three_one_one[three_one_one["is_transport"]]
transport_df
pothole_n = int(transport_df["issue_type"].astype(str).str.upper().eq("POTHOLE").sum())
other_transport_n = len(transport_df) - pothole_n

colors = ["#D9D9D9", "#4C78A8"]
plt.figure(figsize=(8, 8))
plt.pie([pothole_n, other_transport_n],
        labels = ["Potholes", "All other transportation issues"],
        colors = colors,
        autopct = lambda p: f"{p:.1f}%",
        startangle=90,
        explode=(0.1, 0))
plt.title(" 311 Transportation: Pothole VS All Other Transportation Issues",
          fontsize = 18,
          fontweight = "bold",
          pad = 14)
plt.tight_layout()
plt.show()

transport_df.columns.tolist()

potholes_df = transport_df[transport_df["issue_type"].astype(str).str.upper().eq("POTHOLE")].copy()

potholes_path = "/content/mdc_2023_potholes_for_agol_heatmap.csv"
potholes_df.to_csv(potholes_path, index=False)
print(potholes_path)

potholes_df

top10 = (potholes_df["city"].astype(str).value_counts().head(10).sort_values(ascending=True)
)
plt.figure(figsize=(10,6))
plt.barh(top10.index, top10.values)
plt.title("Top 10 Cities by Pothole 311 Requests", fontsize=18, fontweight="bold")
plt.xlabel("Pothole request count")
plt.tight_layout()
plt.show()

potholes_df = pd.read_csv("mdc_2019_potholes.csv")

import pandas as pd


status_counts = potholes_df["ticket_status"].value_counts(dropna=False)
print(status_counts)

# Consider "not fixed" as anything not CLOSED
not_fixed = potholes_df[potholes_df["ticket_status"].astype(str).str.upper().ne("CLOSED")].copy()
print("Not fixed count:", len(not_fixed))

# Export a visible table for StoryMap / appendix
table_cols = [
    "ticket_id", "city", "street_address",
    "ticket_created_date_time", "ticket_closed_date_time",
    "goal_days", "actual_completed_days", "ticket_status",
    "latitude", "longitude"
]
not_fixed[table_cols].to_csv("/content/potholes_not_fixed_2019.csv", index=False)
print("Saved: /content/potholes_not_fixed_2019.csv")

y_16 = pd.read_csv("mdc_2016_potholes.csv")
y_17 = pd.read_csv("mdc_2017_potholes.csv")
y_18 = pd.read_csv("mdc_2018_potholes.csv")
y_19 = pd.read_csv("mdc_2019_potholes.csv")
y_20 = pd.read_csv("mdc_2020_potholes.csv")
y_21 = pd.read_csv("mdc_2021_potholes.csv")
y_22 = pd.read_csv("mdc_2022_potholes.csv")
y_23 = pd.read_csv("mdc_2023_potholes.csv")

y_all =  [y_16,y_17,y_18,y_19,y_20,y_21,y_22,y_23]
potholes_all = pd.concat(y_all)
potholes_all
potholes_all.to_csv("All_pothole_data.csv", index=False)

potholes_all

potholes_all = pd.read_csv("All_pothole_data.csv")
potholes_all["late_flag"] = (potholes_all["delay_days"] > 0).astype(int)
potholes_all["long_tail_flag"] = (potholes_all["actual_completed_days"] >= 30).astype(int)

potholes_all.to_csv("All_pothole_data_with_turnover.csv", index=False)

# Final Dataset with the included two columns

df = pd.read_csv("All_pothole_data.csv")
df["goal_days"] = pd.to_numeric(df["goal_days"], errors="coerce")
df["actual_completed_days"] = pd.to_numeric(df["actual_completed_days"], errors="coerce")
actual_clean = df["actual_completed_days"]
df["delay_days"] = actual_clean - df["goal_days"]
df["late_flag"] = (df["delay_days"] > 0).astype("Int64")
df.to_csv("All_pothole_data_with_delay_late.csv", index=False)

all_potholes_delay = pd.read_csv("All_pothole_data_with_delay_late.csv")
all_potholes_delay.head()

#
#
#Literacy rate (This is for the dashboard assignment)
#Weather